import { useState, useEffect, ReactNode } from "react";
import { Language, LanguageContext } from "./languageContext";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.freeShipping": "Free shipping over $50",
    "header.returns": "30-day returns",
    "header.help": "Help",
    "header.trackOrder": "Track Order",
    "header.sellOn": "Sell on iwanyu",
    "header.search": "Search products, brands, categories...",
    "header.orders": "Orders",
    "header.wishlist": "Wishlist",
    "header.account": "Account",
    "header.cart": "Cart",
    
    // Seller Onboarding
    "sell.title": "Become a Seller 🇷🇼",
    "sell.subtitle": "Join Rwanda's trusted marketplace - Iwanyu",
    "sell.subtext": "Simple steps to open your store in Kigali and beyond",
    "sell.createAccount": "Create your account",
    "sell.createAccountDesc": "First, create your account. This takes less than 1 minute.",
    "sell.rwandaTrust": "Rwanda's trusted marketplace - Sell to customers across Kigali, Musanze, Rubavu, and all of Rwanda!",
    "sell.nextStep": "Next step",
    "sell.afterSignup": "After signing up, verify your email, then take a selfie and upload your Rwandan ID.",
    "sell.createAccountBtn": "Create account",
    "sell.haveAccount": "I have an account",
    "sell.checkEmail": "Check your email",
    "sell.sentLink": "We sent a verification link to",
    "sell.clickLink": "Click the link in the email to confirm your account. Then come back here.",
    "sell.afterConfirm": "After confirming, you will take a selfie and upload your Rwandan ID.",
    "sell.resendEmail": "Send email again",
    "sell.confirmedEmail": "I confirmed my email",
    "sell.verifyIdentity": "Verify your identity",
    "sell.verifyDesc": "Take a selfie and upload your Rwandan National ID. This keeps our marketplace safe for all Rwandans.",
    "sell.selfie": "Your photo (selfie)",
    "sell.selfieDesc": "Take a clear photo of your face. Look directly at the camera.",
    "sell.openCamera": "Open Camera",
    "sell.takePhoto": "Take Photo",
    "sell.cancel": "Cancel",
    "sell.selfieCaptured": "Selfie captured",
    "sell.lookingGood": "Looking good!",
    "sell.retake": "Retake",
    "sell.idFront": "ID card (front)",
    "sell.idFrontDesc": "Take a photo of the front of your Rwandan National ID.",
    "sell.idFrontUploaded": "ID front uploaded",
    "sell.clickToChange": "Click to change",
    "sell.uploadIdFront": "Click to take photo or upload ID front",
    "sell.idBack": "ID card (back) - optional",
    "sell.idBackDesc": "If your Rwandan ID has info on the back, upload it here.",
    "sell.idBackUploaded": "ID back uploaded",
    "sell.uploadIdBack": "Click to upload ID back (optional)",
    "sell.afterPhotos": "After taking photos, you will name your store.",
    "sell.continueToStore": "Continue to store details",
    "sell.createStore": "Create your store",
    "sell.almostDone": "Almost done! Name your store and start selling to Rwandans.",
    "sell.storeName": "Store name",
    "sell.storeNameDesc": "This is the name customers across Rwanda will see.",
    "sell.location": "Location",
    "sell.locationPlaceholder": "Kigali, Musanze, Rubavu...",
    "sell.locationDesc": "Your city or district in Rwanda",
    "sell.phone": "Phone number (optional)",
    "sell.phoneDesc": "Your Rwandan phone number for store inquiries.",
    "sell.uploading": "Uploading images...",
    "sell.createMyStore": "Create my store",
    "sell.creatingStore": "Creating store...",
    "sell.goBack": "Go back to ID upload",
    "sell.storeReady": "Your store is ready!",
    "sell.welcomeRwanda": "Welcome to Rwanda's marketplace! You can now add products and start selling to customers across Kigali, Musanze, Rubavu, and all of Rwanda.",
    "sell.openDashboard": "Open Dashboard",
    "sell.addProducts": "Add products",
    "sell.needHelp": "Need help? Contact us at",
    "sell.cameraError": "Could not open camera. Please check camera permissions in your browser settings.",
    "sell.tryAgain": "Try again",

    // Global UI
    "lang.label": "Language",
    "header.searchButton": "Search",
    "header.sell": "Sell",
    "header.menu": "Menu",
    "header.login": "Log in",
    "header.signup": "Sign up",
    "header.allCategories": "All categories",
    "header.deals": "Deals",
    "header.profile": "Profile",
    "header.myOrders": "My Orders",
    "header.myWishlist": "My Wishlist",
    "header.accountSettings": "Account Settings",
    "header.sellerDashboard": "Seller Dashboard",
    "header.adminDashboard": "Admin Dashboard",
    "header.signOut": "Sign Out",
    "header.paymentsRwf": "Payments in RWF",

    // Hero
    "hero.trusted": "Trusted local sellers",
    "hero.title": "A calmer way to shop Rwanda's best products.",
    "hero.subtitle": "Everything you need, from verified vendors, with fast delivery and secure checkout.",
    "hero.shopCategories": "Shop categories",
    "hero.viewDeals": "View deals",
    "hero.sameWeek": "Same-week delivery",
    "hero.secure": "Secure payments",

    // Category nav
    "category.shopBy": "Shop by Category",
    "category.viewAll": "View all",
    "category.none": "No categories available",

    // Product card
    "product.new": "New",
    "product.noImage": "No Image",
    "product.removeWishlist": "Remove from wishlist",
    "product.addWishlist": "Add to wishlist",
    "product.soldBy": "Sold by",
    "product.add": "Add",
    "product.outOfStock": "Out of stock",
    "product.toastAddedTitle": "✓ Added to cart",
    "product.toastAddedDesc": "has been added to your cart.",
    "product.toastWishAdded": "♥ Added to wishlist",
    "product.toastWishRemoved": "Removed from wishlist",
    "product.toastWishDescAdd": "has been added to your wishlist.",
    "product.toastWishDescRemove": "has been removed from your wishlist.",
    "product.toastWishFail": "⚠ Wishlist update failed",
    "product.toastTryAgain": "Please try again.",

    // Home page
    "home.recentlyViewed": "Recently viewed",
    "home.pickup": "Pick up where you left off.",
    "home.clear": "Clear",
    "home.noProducts": "No products available",
    "home.noProductsDesc": "No products to show yet.",
    "home.tryAgain": "Try again in a moment.",
    "home.reload": "Reload",
    "home.freeShipTitle": "Free shipping on your first order",
    "home.freeShipDesc": "Create an account to unlock perks and faster checkout.",
    "home.createAccount": "Create account",

    // Footer
    "footer.sellTitle": "Sell on iwanyu",
    "footer.sellDesc": "Reach more customers across Rwanda with verified, trusted storefronts.",
    "footer.startSelling": "Start selling",
    "footer.tagline": "Rwanda's marketplace connecting buyers with trusted vendors.",
    "footer.shop": "Shop",
    "footer.allProducts": "All products",
    "footer.newArrivals": "New arrivals",
    "footer.categories": "Categories",
    "footer.company": "Company",
    "footer.about": "About",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.support": "Support",
    "footer.helpCenter": "Help center",
    "footer.trackOrder": "Track order",
    "footer.contact": "Contact",
    "footer.securePayments": "Secure payments",
    "footer.protectedCheckout": "Protected checkout",

    // Login / Signup
    "auth.signIn": "Sign in",
    "auth.signingIn": "Signing in...",
    "auth.createAccount": "Create account",
    "auth.creatingAccount": "Creating account...",
    "auth.signUp": "Sign up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.fullNameOptional": "Full name (optional)",
    "auth.signinSubtitle": "Sign in to manage your account and sell products.",
    "auth.signupSubtitle": "Sign up to shop and sell on iwanyu marketplace.",
    "auth.continueWithGoogle": "Continue with Google",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.continueShopping": "Continue shopping",
    "auth.supabaseNotConfigured": "Supabase auth is not configured",
    "auth.configureKeys": "Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.",
    "auth.signinFailed": "Sign in failed",
    "auth.signupFailed": "Sign up failed",

    // Cart
    "cart.title": "Shopping Cart",
    "cart.items": "item",
    "cart.itemsPlural": "items",
    "cart.continue": "Continue shopping",
    "cart.empty": "Your cart is empty.",
    "cart.shopProducts": "Shop products",
    "cart.noImage": "No image",
    "cart.remove": "Remove",
    "cart.decrease": "Decrease",
    "cart.increase": "Increase",
    "cart.total": "Total",
    "cart.clear": "Clear cart",
    "cart.checkout": "Checkout",
    "cart.orderSummary": "Order summary",
    "cart.subtotal": "Subtotal",
    "cart.serviceFee": "Service fee",
    "cart.shipping": "Shipping",
    "cart.calculated": "Calculated",
    "cart.proceed": "Proceed to checkout",
    "cart.recommended": "Recommended products",
    "cart.noRecommendations": "No recommendations available right now.",

    // Checkout
    "checkout.emptyTitle": "Your cart is empty",
    "checkout.emptyDesc": "Add some items to get started",
    "checkout.startShopping": "Start Shopping",
    "checkout.backToCart": "Back to cart",
    "checkout.secure": "Secure checkout",
    "checkout.contactInfo": "Contact Information",
    "checkout.emailAddress": "Email address",
    "checkout.phone": "Phone number",
    "checkout.phoneHint": "For delivery updates and Mobile Money payments",
    "checkout.shippingAddress": "Shipping Address",
    "checkout.streetAddress": "Street address",
    "checkout.cityDistrict": "City / District",
    "checkout.paymentMethod": "Payment Method",
    "checkout.paymentSubtitle": "Secure payment powered by Flutterwave",
    "checkout.mobileMoney": "Mobile Money",
    "checkout.mobileMoneyHint": "MTN MoMo / Airtel Money",
    "checkout.card": "Debit / Credit Card",
    "checkout.cardHint": "Visa, Mastercard",
    "checkout.redirectHint": "You'll be redirected to Flutterwave's secure payment page to complete your payment.",
    "checkout.orderSummary": "Order Summary",
    "checkout.qty": "Qty",
    "checkout.discountCode": "Discount code",
    "checkout.apply": "Apply",
    "checkout.discountApplied": "Applied",
    "checkout.remove": "Remove",
    "checkout.discountFailed": "Discount failed",
    "checkout.discount": "Discount",
    "checkout.free": "Free",
    "checkout.processing": "Processing...",
    "checkout.pay": "Pay",
    "checkout.sslSecured": "SSL Secured",
    "checkout.buyerProtection": "Buyer Protection",
    "checkout.checkoutFailed": "Checkout failed",
    "checkout.discountAppliedToast": "Discount applied",

    // Account
    "account.title": "My Account",
    "account.subtitle": "Manage your account settings and preferences",
    "account.signInTitle": "Sign in to manage your account",
    "account.signInDesc": "Your profile, orders, and wishlist are tied to your account.",
    "account.goToLogin": "Go to login",
    "account.unavailableTitle": "Profile is unavailable",
    "account.unavailableDesc": "Database connection is not configured.",
    "account.menu": "Account Menu",
    "account.profile": "Profile",
    "account.quickLinks": "Quick Links",
    "account.viewOrders": "View orders",
    "account.sellerDashboard": "Seller dashboard",
    "account.adminDashboard": "Admin dashboard",
    "account.developer": "Developer",
    "account.roleSwitcher": "Role switcher (dev only).",
    "account.current": "Current",
    "account.profileInfo": "Profile Information",
    "account.fullName": "Full Name",
    "account.phoneNumber": "Phone Number",
    "account.emailAddress": "Email Address",
    "account.address": "Address",
    "account.city": "City",
    "account.country": "Country",
    "account.saveProfile": "Save profile",
    "account.saving": "Saving...",
    "account.refresh": "Refresh account",
    "account.refreshing": "Refreshing...",
    "account.stats": "Account Statistics",
    "account.totalOrders": "Total Orders",
    "account.wishlistItems": "Wishlist Items",
    "account.savedAddresses": "Saved Addresses",
    "account.profileSaved": "✓ Profile saved",
    "account.profileSavedDesc": "Your profile has been updated successfully.",
    "account.profileSaveFailed": "⚠ Could not save profile",
    "account.tryAgain": "Please try again.",
    "account.refreshed": "Refreshed",
    "account.refreshedDesc": "Account and role reloaded.",
    "account.refreshFailed": "Refresh failed",
    "account.roleUpdated": "Role updated",
    "account.roleBuyer": "You are now a buyer.",
    "account.roleSeller": "You are now a seller.",
    "account.roleAdmin": "You are now an admin.",
    "account.roleUpdateFailed": "Role update failed",
    "account.buyer": "Buyer",
    "account.seller": "Seller",
    "account.admin": "Admin",

    // Orders
    "orders.title": "Your Orders",
    "orders.subtitle": "Track and manage your orders",
    "orders.signInTitle": "Sign in to see your orders",
    "orders.signInDesc": "Your order history, tracking information, and purchase details are available after signing in.",
    "orders.signIn": "Sign In",
    "orders.unavailable": "Orders are not available",
    "orders.noneTitle": "No orders yet",
    "orders.noneDesc": "When you make a purchase, your orders will appear here. Start shopping to see your order history!",
    "orders.startShopping": "Start Shopping",
    "orders.date": "Date",
    "orders.total": "Total",
    "orders.dbNotConfigured": "Database connection is not configured.",

    // Seller dashboard/pages
    "seller.accessRestricted": "Access Restricted",
    "seller.loginRequired": "You must be logged in to view this page.",
    "seller.accountNeeded": "Seller account needed",
    "seller.accountNeededDesc": "Create your seller account to use this dashboard.",
    "seller.startSelling": "Start selling",
    "seller.returnHome": "Return Home",
    "seller.dashboard": "Dashboard",
    "seller.goToStore": "Go to store",
    "seller.overview": "Overview",
    "seller.overviewDesc": "Simple view of your store.",
    "seller.sales": "Sales",
    "seller.orders": "Orders",
    "seller.products": "Products",
    "seller.notifications": "Notifications",
    "seller.noNotifications": "No new notifications.",
    "seller.quickActions": "Quick actions",
    "seller.addProduct": "Add product",
    "seller.addProductDesc": "Create a new listing",
    "seller.viewOrders": "View orders",
    "seller.viewOrdersDesc": "See and update orders",
    "seller.storeSettings": "Store settings",
    "seller.storeSettingsDesc": "Update store details",
    "seller.productsTitle": "Seller Products",
    "seller.productsSubtitle": "Create and manage vendor listings.",
    "seller.newProduct": "New product",
    "seller.vendor": "Vendor",
    "seller.unknown": "Unknown",
    "seller.price": "Price",
    "seller.stock": "Stock",
    "seller.inStock": "In stock",
    "seller.out": "Out",
    "seller.view": "View",
    "seller.deleted": "Deleted",
    "seller.productRemoved": "Product removed.",
    "seller.deleteFailed": "Delete failed",
    "seller.unknownError": "Unknown error",
    "seller.delete": "Delete",
    "seller.ordersLoadFailed": "Failed to load orders",
    "seller.ordersTitle": "Seller Orders",
    "seller.ordersSubtitle": "Manage fulfillment and status updates.",
    "seller.loading": "Loading...",
    "seller.fetchingOrders": "Fetching orders.",
    "seller.noOrdersYet": "No orders yet",
    "seller.noOrdersDesc": "Orders containing your products will appear here.",
    "seller.order": "Order",
    "seller.buyer": "Buyer",
    "seller.total": "Total",
    "seller.yourItems": "Your items",
    "seller.orderStatus": "Order status",
    "seller.items": "Items",
    "seller.qty": "Qty",
    "seller.updateFailed": "Update failed",
    "seller.payoutsTitle": "Payouts & Wallet",
    "seller.payoutsSubtitle": "Manage your earnings and withdrawal methods.",
    "seller.backToDashboard": "Back to Dashboard",
    "seller.availableBalance": "Available Balance",
    "seller.withdrawFunds": "Withdraw Funds",
    "seller.payoutSettings": "Payout Settings",
    "seller.nextScheduledPayout": "Next Scheduled Payout",
    "seller.nextMonday": "Next Monday",
    "seller.automaticTransfer": "Automatic transfer",
    "seller.processingPeriod": "Processing period",
    "seller.transactionHistory": "Transaction History",
    "seller.date": "Date",
    "seller.type": "Type",
    "seller.description": "Description",
    "seller.reference": "Reference",
    "seller.amount": "Amount",
    "seller.status": "Status",
    "seller.payout": "Payout",
    "seller.sale": "Sale",
    "seller.weeklySettlement": "Weekly Settlement",
    "seller.completed": "Completed",
    "seller.storeSettingsPageDesc": "Manage your store profile and preferences.",
    "seller.storeInformation": "Store Information",
    "seller.storeName": "Store Name",
    "seller.supportEmail": "Support Email",
    "seller.storeDescription": "Store Description",
    "seller.describeStore": "Describe your store...",
    "seller.branding": "Branding",
    "seller.uploadLogo": "Upload Logo",
    "seller.uploadBanner": "Upload Banner Image",
    "seller.saveChanges": "Save Changes",
    "sellerNew.unsupportedFile": "Unsupported file",
    "sellerNew.fileTooLarge": "File too large",
    "sellerNew.exceedsUploadLimit": "exceeds the upload limit",
    "sellerNew.createProduct": "Create product",
    "sellerNew.fastSetup": "Fast setup with media preview and simple variants.",
    "sellerNew.back": "Back",
    "sellerNew.basics": "Basics",
    "sellerNew.noApprovedStore": "No approved store yet",
    "sellerNew.submitVendorApplication": "Submit your vendor application on the onboarding page first.",
    "sellerNew.goToOnboarding": "Go to onboarding",
    "sellerNew.vendor": "Vendor",
    "sellerNew.chooseVendor": "Choose vendor",
    "sellerNew.noStoreYet": "No store yet. Create one below.",
    "sellerNew.orCreateVendor": "Or create vendor",
    "sellerNew.vendorName": "Vendor name",
    "sellerNew.vendorRequiresApproval": "Vendors require admin approval. Use onboarding.",
    "sellerNew.title": "Title",
    "sellerNew.titlePlaceholder": "e.g. Classic cotton t-shirt",
    "sellerNew.description": "Description",
    "sellerNew.descriptionPlaceholder": "Short, clear description. Include material, fit, what’s included.",
    "sellerNew.category": "Category",
    "sellerNew.noCategories": "No categories available.",
    "sellerNew.selectCategory": "Select category",
    "sellerNew.priceRwf": "Price (RWF)",
    "sellerNew.stock": "Stock",
    "sellerNew.discountPercent": "Discount (%)",
    "sellerNew.media": "Media",
    "sellerNew.imagesVideos": "Images & videos",
    "sellerNew.dragDrop": "Drag & drop, or choose files. Up to",
    "sellerNew.imagesMax": "Images ≤",
    "sellerNew.videosMax": "videos ≤",
    "sellerNew.addMedia": "Add media",
    "sellerNew.setAsPrimary": "Set as primary",
    "sellerNew.primary": "Primary",
    "sellerNew.removeMedia": "Remove media",
    "sellerNew.noMediaYet": "No media selected yet.",
    "sellerNew.variants": "Variants",
    "sellerNew.disable": "Disable",
    "sellerNew.enable": "Enable",
    "sellerNew.variantsHelp": "Add common options (like colors and sizes). These help buyers choose quickly.",
    "sellerNew.colors": "Colors",
    "sellerNew.addColorPlaceholder": "Add a color (e.g. Blue or #3b82f6)",
    "sellerNew.sizes": "Sizes",
    "sellerNew.addSizePlaceholder": "Add a size (e.g. XXL)",
    "sellerNew.variantsDisabled": "Variants are disabled. Product will be listed without selectable options.",
    "sellerNew.readyToPublish": "Ready to publish",
    "sellerNew.looksGood": "Looks good",
    "sellerNew.publishChecklist": "Add title, price, category, and vendor to publish.",
    "sellerNew.colorsLower": "colors",
    "sellerNew.sizesLower": "sizes",
    "sellerNew.off": "Off",
    "sellerNew.selectCategoryError": "Please select a category",
    "sellerNew.vendorCreationRequiresApproval": "Vendor creation requires approval. Use onboarding (/sell).",
    "sellerNew.missingVendor": "Missing vendor",
    "sellerNew.missingSession": "Missing session",
    "sellerNew.productUploaded": "Product uploaded",
    "sellerNew.productLive": "Your product is live.",
    "sellerNew.uploadFailed": "Upload failed",
    "sellerNew.uploading": "Uploading...",
    "sellerNew.publishProduct": "Publish product",
    "sellerNew.uploadingMedia": "Uploading media...",
    "sellerNew.complete": "complete",

    // Admin dashboard/pages
    "admin.signInRequired": "Sign In Required",
    "admin.authRequired": "Admin authentication needed",
    "admin.accessDenied": "Access Denied",
    "admin.privilegesRequired": "Admin privileges required",
    "admin.home": "Home",
    "admin.account": "Account",
    "admin.supabaseMissing": "Supabase is not configured",
    "admin.missingData": "Missing data",
    "admin.notSignedIn": "Not signed in",
    "admin.missingVendor": "Missing vendor",
    "admin.missingProduct": "Missing product",
    "admin.reasonMin": "Please provide a short reason (min 5 chars)",
    "admin.panel": "Admin Panel",
    "admin.storefront": "Store front",
    "admin.dashboardOverview": "Dashboard Overview",
    "admin.vendors": "Vendors",
    "admin.products": "Products",
    "admin.discounts": "Discounts",
    "admin.applications": "Applications",
    "admin.approved": "Approved",
    "admin.pending": "Pending",
    "admin.rejected": "Rejected",
    "admin.revoked": "Revoked",
    "admin.category": "Category",
    "admin.stock": "Stock",
    "admin.allCategories": "All Categories",
    "admin.allStock": "All Stock",
    "admin.inStock": "In Stock",
    "admin.outOfStock": "Out of Stock",
    "admin.totalProducts": "total products",
    "admin.totalVendors": "total vendors",
    "admin.totalValue": "Total Value",
    "admin.totalSales": "Total sales",
    "admin.totalSold": "Total Sold",
    "admin.unitsSold": "Units sold",
    "admin.sold": "sold",
    "admin.search": "Search...",
    "admin.searchVendors": "Search vendors...",
    "admin.searchCodes": "Search codes...",
    "admin.noProductsFound": "No products found",
    "admin.noVendorsFound": "No vendors found",
    "admin.noApplicationsFound": "No applications found",
    "admin.vendorApplications": "Vendor Applications",
    "admin.totalApplications": "total applications",
    "admin.loadingApplications": "Loading applications...",
    "admin.noLocation": "No location",
    "admin.noLocationSpecified": "No location specified",
    "admin.applied": "Applied",
    "admin.user": "User",
    "admin.canNowSell": "can now sell",
    "admin.isNowApproved": "is now approved",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.restore": "Restore",
    "admin.revoke": "Revoke",
    "admin.vendorCanSellAgain": "Vendor can sell again",
    "admin.vendorCannotSell": "Vendor cannot sell",
    "admin.removeVendor": "Remove vendor",
    "admin.sales": "Sales",
    "admin.revenue": "Revenue",
    "admin.discountCode": "Discount code",
    "admin.discountCodes": "Discount Codes",
    "admin.createDiscountCode": "Create Discount Code",
    "admin.created": "Created",
    "admin.createdLower": "created",
    "admin.code": "Code",
    "admin.codeMin": "Code must be at least 3 characters",
    "admin.description": "Description",
    "admin.type": "Type",
    "admin.percentage": "Percentage",
    "admin.fixedAmountRwf": "Fixed amount (RWF)",
    "admin.value": "Value",
    "admin.minSubtotal": "Min subtotal",
    "admin.minSubtotalRwf": "Min subtotal (RWF)",
    "admin.maxRedemptionsOptional": "Max redemptions (optional)",
    "admin.redeemed": "Redeemed",
    "admin.actions": "Actions",
    "admin.create": "Create",
    "admin.deleteCodeConfirm": "Delete code",
    "admin.updated": "Updated",
    "admin.deleted": "Deleted",
    "admin.failed": "Failed",
    "admin.unknownError": "Unknown error",
    "admin.deleteProduct": "Delete Product",
    "admin.deleteProductDesc": "This will remove the product and notify the vendor.",
    "admin.productRemoved": "Product removed",
    "admin.deleteVendor": "Delete Vendor",
    "admin.deleteVendorDesc": "This will remove the vendor and unlist all their products. Existing orders remain intact.",
    "admin.vendorRemoved": "Vendor removed",
    "admin.reasonForRemoval": "Reason for removal",
    "admin.explainPolicy": "Explain policy violation...",
    "admin.cancel": "Cancel",
    "admin.all": "All",
    "admin.missingCategory": "Missing category",
    "auth.login": "Log in",
  },
  rw: {
    // Header
    "header.freeShipping": "Kohereza ku buntu hejuru ya $50",
    "header.returns": "Gusubiza mu minsi 30",
    "header.help": "Ubufasha",
    "header.trackOrder": "Kurikirana Order",
    "header.sellOn": "Gurisha kuri iwanyu",
    "header.search": "Shakisha ibicuruzwa, amazina, categories...",
    "header.orders": "Orders",
    "header.wishlist": "Ibyashimwe",
    "header.account": "Konti",
    "header.cart": "Agaseke",
    
    // Seller Onboarding
    "sell.title": "Gura no Kugurisha mu Rwanda 🇷🇼",
    "sell.subtitle": "Injira muri Iwanyu - Isoko ry'u Rwanda",
    "sell.subtext": "Intambwe zoroshye zo gufungura iduka ryawe i Kigali n'ahandi",
    "sell.createAccount": "Fungura Konti yawe",
    "sell.createAccountDesc": "Banza ufungure konti. Bifata munsi y'umunota 1.",
    "sell.rwandaTrust": "Isoko ry'u Rwanda ryizewe - Gurisha abakiriya bo mu Kigali, Musanze, Rubavu, no mu Rwanda hose!",
    "sell.nextStep": "Intambwe ikurikira",
    "sell.afterSignup": "Nyuma yo kwiyandikisha, emeza email yawe, hanyuma ufate selfie kandi ushyiremo indangamuntu y'u Rwanda.",
    "sell.createAccountBtn": "Fungura konti",
    "sell.haveAccount": "Mfite konti",
    "sell.checkEmail": "Reba email yawe",
    "sell.sentLink": "Twohereje link kuri",
    "sell.clickLink": "Kanda link iri muri email kugirango wemeze konti yawe. Hanyuma ugaruke hano.",
    "sell.afterConfirm": "Nyuma yo kwemeza, uzafata selfie kandi ushyiremo indangamuntu y'u Rwanda.",
    "sell.resendEmail": "Ohereza email ukundi",
    "sell.confirmedEmail": "Nasuzumye email yanjye",
    "sell.verifyIdentity": "Emeza ko uri wowe",
    "sell.verifyDesc": "Fata selfie kandi ushyiremo indangamuntu y'u Rwanda. Ibi bikomeza isoko ryacu rikingira Abanyarwanda bose.",
    "sell.selfie": "Ifoto yawe (selfie)",
    "sell.selfieDesc": "Fata ifoto isobanutse y'isura yawe. Reba camera.",
    "sell.openCamera": "Fungura Camera",
    "sell.takePhoto": "Fata Ifoto",
    "sell.cancel": "Kureka",
    "sell.selfieCaptured": "Selfie yafashwe",
    "sell.lookingGood": "Isa neza!",
    "sell.retake": "Fata ukundi",
    "sell.idFront": "Indangamuntu (imbere)",
    "sell.idFrontDesc": "Fata ifoto y'imbere y'indangamuntu y'u Rwanda.",
    "sell.idFrontUploaded": "Imbere y'ID yashyizwe",
    "sell.clickToChange": "Kanda guhindura",
    "sell.uploadIdFront": "Kanda gufata ifoto cyangwa gushyiramo ID imbere",
    "sell.idBack": "Indangamuntu (inyuma) - optional",
    "sell.idBackDesc": "Niba indangamuntu y'u Rwanda ifite amakuru inyuma, shyira hano.",
    "sell.idBackUploaded": "Inyuma y'ID yashyizwe",
    "sell.uploadIdBack": "Kanda gushyiramo inyuma ya ID (optional)",
    "sell.afterPhotos": "Nyuma yo gufata amafoto, uzahe izina iduka ryawe.",
    "sell.continueToStore": "Komeza ku makuru y'iduka",
    "sell.createStore": "Shyiraho iduka ryawe",
    "sell.almostDone": "Birakugerageje! Ita izina iduka ryawe uhereye kugurisha Abanyarwanda.",
    "sell.storeName": "Izina ry'iduka",
    "sell.storeNameDesc": "Iri ni izina abakiriya bo mu Rwanda bazabona.",
    "sell.location": "Aho uherereye",
    "sell.locationPlaceholder": "Kigali, Musanze, Rubavu...",
    "sell.locationDesc": "Umujyi cyangwa akarere kawe mu Rwanda",
    "sell.phone": "Telefoni (optional)",
    "sell.phoneDesc": "Nimero yawe y'u Rwanda yo kubazwa ku iduka.",
    "sell.uploading": "Gushyiramo amafoto...",
    "sell.createMyStore": "Shyiraho iduka ryanjye",
    "sell.creatingStore": "Gushyiraho iduka...",
    "sell.goBack": "Subira ku gushyiramo ID",
    "sell.storeReady": "Iduka ryawe rirakora! 🎉",
    "sell.welcomeRwanda": "Murakaza neza mu isoko ry'u Rwanda! Ubu ushobora kongeramo ibicuruzwa no gutangira kugurisha abakiriya bo i Kigali, Musanze, Rubavu, no mu Rwanda hose.",
    "sell.openDashboard": "Fungura Dashboard",
    "sell.addProducts": "Shyiraho ibicuruzwa",
    "sell.needHelp": "Ukeneye ubufasha? Twandikire kuri",
    "sell.cameraError": "Ntitwashoboye gufungura camera. Reba niba wemeye camera muri settings.",
    "sell.tryAgain": "Gerageza ukundi",

    // Global UI
    "lang.label": "Ururimi",
    "header.searchButton": "Shaka",
    "header.sell": "Gurisha",
    "header.menu": "Menu",
    "header.login": "Injira",
    "header.signup": "Iyandikishe",
    "header.allCategories": "Ibyiciro byose",
    "header.deals": "Ibigabanywa",
    "header.profile": "Umwirondoro",
    "header.myOrders": "Orders zanjye",
    "header.myWishlist": "Ibyifuzo byanjye",
    "header.accountSettings": "Igenamiterere rya konti",
    "header.sellerDashboard": "Dashboard y'umucuruzi",
    "header.adminDashboard": "Dashboard y'admin",
    "header.signOut": "Sohoka",
    "header.paymentsRwf": "Kwishyura muri RWF",

    // Hero
    "hero.trusted": "Abacuruzi b'aho hizewe",
    "hero.title": "Uburyo bworoshye bwo guhaha ibicuruzwa byiza byo mu Rwanda.",
    "hero.subtitle": "Byose ukeneye, biturutse ku bacuruzi bemejwe, kohereza byihuse no kwishyura bitekanye.",
    "hero.shopCategories": "Gura mu byiciro",
    "hero.viewDeals": "Reba ibigabanywa",
    "hero.sameWeek": "Koherezwa muri iki cyumweru",
    "hero.secure": "Kwishyura bitekanye",

    // Category nav
    "category.shopBy": "Gura ukurikije icyiciro",
    "category.viewAll": "Reba byose",
    "category.none": "Nta byiciro bihari",

    // Product card
    "product.new": "Gishya",
    "product.noImage": "Nta foto",
    "product.removeWishlist": "Kuramo ku byifuzo",
    "product.addWishlist": "Shyira ku byifuzo",
    "product.soldBy": "Gicuruzwa na",
    "product.add": "Ongeramo",
    "product.outOfStock": "Ntikirimo",
    "product.toastAddedTitle": "✓ Byongewe mu gaseke",
    "product.toastAddedDesc": "byongewe mu gaseke kawe.",
    "product.toastWishAdded": "♥ Byongewe ku byifuzo",
    "product.toastWishRemoved": "Byakuwe ku byifuzo",
    "product.toastWishDescAdd": "byongewe ku byifuzo byawe.",
    "product.toastWishDescRemove": "byakuwe ku byifuzo byawe.",
    "product.toastWishFail": "⚠ Kuvugurura ibyifuzo byanze",
    "product.toastTryAgain": "Gerageza kongera.",

    // Home page
    "home.recentlyViewed": "Ibyo uherutse kureba",
    "home.pickup": "Komereza aho wari ugeze.",
    "home.clear": "Siba",
    "home.noProducts": "Nta bicuruzwa bihari",
    "home.noProductsDesc": "Nta bicuruzwa byo kwerekana ubu.",
    "home.tryAgain": "Gerageza nyuma gato.",
    "home.reload": "Ongera ufungure",
    "home.freeShipTitle": "Kohereza ku buntu ku order ya mbere",
    "home.freeShipDesc": "Fungura konti ubone ibyiza no kwishyura byihuse.",
    "home.createAccount": "Fungura konti",

    // Footer
    "footer.sellTitle": "Gurisha kuri iwanyu",
    "footer.sellDesc": "Gera ku bakiriya benshi mu Rwanda ukoresheje iduka ryizewe kandi ryemejwe.",
    "footer.startSelling": "Tangira kugurisha",
    "footer.tagline": "Isoko ry'u Rwanda rihuza abagura n'abacuruzi bizewe.",
    "footer.shop": "Guhaha",
    "footer.allProducts": "Ibicuruzwa byose",
    "footer.newArrivals": "Ibishya",
    "footer.categories": "Ibyiciro",
    "footer.company": "Ikigo",
    "footer.about": "Abo turi bo",
    "footer.privacy": "Ubwirinzi bw'amakuru",
    "footer.terms": "Amabwiriza",
    "footer.support": "Ubufasha",
    "footer.helpCenter": "Ikigo cy'ubufasha",
    "footer.trackOrder": "Kurikirana order",
    "footer.contact": "Twandikire",
    "footer.securePayments": "Kwishyura bitekanye",
    "footer.protectedCheckout": "Checkout irinzwe",

    // Login / Signup
    "auth.signIn": "Injira",
    "auth.signingIn": "Kwinjira...",
    "auth.createAccount": "Fungura konti",
    "auth.creatingAccount": "Gukora konti...",
    "auth.signUp": "Iyandikishe",
    "auth.email": "Imeyili",
    "auth.password": "Ijambobanga",
    "auth.fullNameOptional": "Amazina yose (si ngombwa)",
    "auth.signinSubtitle": "Injira ucunge konti yawe kandi ugurishe ibicuruzwa.",
    "auth.signupSubtitle": "Iyandikishe kugira ngo uhaha kandi ugurishe kuri iwanyu.",
    "auth.continueWithGoogle": "Komeza na Google",
    "auth.noAccount": "Nta konti ufite?",
    "auth.haveAccount": "Usanzwe ufite konti?",
    "auth.continueShopping": "Komeza guhaha",
    "auth.supabaseNotConfigured": "Supabase auth ntirashyirwaho",
    "auth.configureKeys": "Shyiraho VITE_SUPABASE_URL na VITE_SUPABASE_ANON_KEY.",
    "auth.signinFailed": "Kwinjira byanze",
    "auth.signupFailed": "Kwiyandikisha byanze",

    // Cart
    "cart.title": "Agaseke",
    "cart.items": "igicuruzwa",
    "cart.itemsPlural": "ibicuruzwa",
    "cart.continue": "Komeza guhaha",
    "cart.empty": "Agaseke kawe karimo ubusa.",
    "cart.shopProducts": "Gura ibicuruzwa",
    "cart.noImage": "Nta foto",
    "cart.remove": "Kuraho",
    "cart.decrease": "Gabanya",
    "cart.increase": "Ongera",
    "cart.total": "Igiteranyo",
    "cart.clear": "Siba agaseke",
    "cart.checkout": "Kwishyura",
    "cart.orderSummary": "Incamake ya order",
    "cart.subtotal": "Igiteranyo cy'ibicuruzwa",
    "cart.serviceFee": "Amafaranga ya serivisi",
    "cart.shipping": "Kohereza",
    "cart.calculated": "Birabarwa",
    "cart.proceed": "Komeza wishyure",
    "cart.recommended": "Ibicuruzwa dusaba",
    "cart.noRecommendations": "Nta byifuzo biboneka ubu.",

    // Checkout
    "checkout.emptyTitle": "Agaseke kawe karimo ubusa",
    "checkout.emptyDesc": "Ongeramo ibicuruzwa utangire",
    "checkout.startShopping": "Tangira guhaha",
    "checkout.backToCart": "Subira ku gaseke",
    "checkout.secure": "Kwishyura kurinzwe",
    "checkout.contactInfo": "Amakuru yo kuvugana",
    "checkout.emailAddress": "Imeyili",
    "checkout.phone": "Telefoni",
    "checkout.phoneHint": "Kugira ngo ubone amakuru y'itangwa na Mobile Money",
    "checkout.shippingAddress": "Aho woherezwa",
    "checkout.streetAddress": "Aderesi y'umuhanda",
    "checkout.cityDistrict": "Umujyi / Akarere",
    "checkout.paymentMethod": "Uburyo bwo kwishyura",
    "checkout.paymentSubtitle": "Kwishyura kurinzwe na Flutterwave",
    "checkout.mobileMoney": "Mobile Money",
    "checkout.mobileMoneyHint": "MTN MoMo / Airtel Money",
    "checkout.card": "Karita ya banki",
    "checkout.cardHint": "Visa, Mastercard",
    "checkout.redirectHint": "Urahita ujyanwa ku rubuga rwo kwishyura rwa Flutterwave rurinzwe kugirango urangize kwishyura.",
    "checkout.orderSummary": "Incamake ya order",
    "checkout.qty": "Ingano",
    "checkout.discountCode": "Kode y'igabanywa",
    "checkout.apply": "Shyiraho",
    "checkout.discountApplied": "Byashyizweho",
    "checkout.remove": "Kuraho",
    "checkout.discountFailed": "Gukoresha igabanywa byanze",
    "checkout.discount": "Igabanywa",
    "checkout.free": "Ubuntu",
    "checkout.processing": "Birimo gutunganywa...",
    "checkout.pay": "Ishyura",
    "checkout.sslSecured": "SSL Irinzwe",
    "checkout.buyerProtection": "Uburinzi bw'umuguzi",
    "checkout.checkoutFailed": "Kwishyura byanze",
    "checkout.discountAppliedToast": "Igabanywa ryashyizweho",

    // Account
    "account.title": "Konti yanjye",
    "account.subtitle": "Cunga igenamiterere n'ibyo ukunda kuri konti yawe",
    "account.signInTitle": "Injira ucunge konti yawe",
    "account.signInDesc": "Umwirondoro wawe, orders n'ibyifuzo bifitanye isano na konti yawe.",
    "account.goToLogin": "Jya ku kwinjira",
    "account.unavailableTitle": "Umwirondoro ntuboneka",
    "account.unavailableDesc": "Kwihuza na database ntikurashyirwaho.",
    "account.menu": "Menu ya konti",
    "account.profile": "Umwirondoro",
    "account.quickLinks": "Amahitamo yihuse",
    "account.viewOrders": "Reba orders",
    "account.sellerDashboard": "Dashboard y'umucuruzi",
    "account.adminDashboard": "Dashboard y'admin",
    "account.developer": "Umutekinisiye",
    "account.roleSwitcher": "Guhindura role (dev gusa).",
    "account.current": "Ubu",
    "account.profileInfo": "Amakuru y'umwirondoro",
    "account.fullName": "Amazina yose",
    "account.phoneNumber": "Nimero ya telefoni",
    "account.emailAddress": "Imeyili",
    "account.address": "Aderesi",
    "account.city": "Umujyi",
    "account.country": "Igihugu",
    "account.saveProfile": "Bika umwirondoro",
    "account.saving": "Birimo kubika...",
    "account.refresh": "Ongera usubize",
    "account.refreshing": "Birimo gusubirwamo...",
    "account.stats": "Imibare ya konti",
    "account.totalOrders": "Orders zose",
    "account.wishlistItems": "Ibiri ku byifuzo",
    "account.savedAddresses": "Aderesi zabitswe",
    "account.profileSaved": "✓ Umwirondoro wabitswe",
    "account.profileSavedDesc": "Umwirondoro wawe wavuguruwe neza.",
    "account.profileSaveFailed": "⚠ Kubika umwirondoro byanze",
    "account.tryAgain": "Gerageza ukundi.",
    "account.refreshed": "Byasubiwemo",
    "account.refreshedDesc": "Konti na role byongeye kuvugururwa.",
    "account.refreshFailed": "Gusubiramo byanze",
    "account.roleUpdated": "Role yahindutse",
    "account.roleBuyer": "Ubu uri buyer.",
    "account.roleSeller": "Ubu uri seller.",
    "account.roleAdmin": "Ubu uri admin.",
    "account.roleUpdateFailed": "Guhindura role byanze",
    "account.buyer": "Buyer",
    "account.seller": "Seller",
    "account.admin": "Admin",

    // Orders
    "orders.title": "Orders zawe",
    "orders.subtitle": "Kurikirana kandi ucunge orders zawe",
    "orders.signInTitle": "Injira urebe orders zawe",
    "orders.signInDesc": "Amateka yawe ya order, amakuru yo gukurikirana, n'ibyo waguze biboneka umaze kwinjira.",
    "orders.signIn": "Injira",
    "orders.unavailable": "Orders ntiziboneka",
    "orders.noneTitle": "Nta order uragira",
    "orders.noneDesc": "Niwamara kugura, orders zawe zizagaragara hano. Tangira guhaha ubone amateka yawe!",
    "orders.startShopping": "Tangira guhaha",
    "orders.date": "Itariki",
    "orders.total": "Igiteranyo",
    "orders.dbNotConfigured": "Kwihuza na database ntikurashyirwaho.",

    // Seller dashboard/pages
    "seller.accessRestricted": "Uburenganzira buke",
    "seller.loginRequired": "Ugomba kuba winjiye kugira ngo urebe uru rupapuro.",
    "seller.accountNeeded": "Konti ya seller irakenewe",
    "seller.accountNeededDesc": "Fungura konti ya seller kugira ngo ukoreshe uru rubuga.",
    "seller.startSelling": "Tangira kugurisha",
    "seller.returnHome": "Subira ku rubuga nyamukuru",
    "seller.dashboard": "Dashboard",
    "seller.goToStore": "Jya ku iduka",
    "seller.overview": "Incamake",
    "seller.overviewDesc": "Icyerekezo cyoroheje cy'iduka ryawe.",
    "seller.sales": "Ibyagurishijwe",
    "seller.orders": "Orders",
    "seller.products": "Ibicuruzwa",
    "seller.notifications": "Amatangazo",
    "seller.noNotifications": "Nta matangazo mashya.",
    "seller.quickActions": "Ibikorwa byihuse",
    "seller.addProduct": "Ongeraho igicuruzwa",
    "seller.addProductDesc": "Kora listing nshya",
    "seller.viewOrders": "Reba orders",
    "seller.viewOrdersDesc": "Reba kandi uvugurure orders",
    "seller.storeSettings": "Igenamiterere ry'iduka",
    "seller.storeSettingsDesc": "Vugurura amakuru y'iduka",
    "seller.productsTitle": "Ibicuruzwa by'umucuruzi",
    "seller.productsSubtitle": "Kora kandi ucunge listings.",
    "seller.newProduct": "Igicuruzwa gishya",
    "seller.vendor": "Vendor",
    "seller.unknown": "Ntibizwi",
    "seller.price": "Igiciro",
    "seller.stock": "Ububiko",
    "seller.inStock": "Birahari",
    "seller.out": "Byarangiye",
    "seller.view": "Reba",
    "seller.deleted": "Byasibwe",
    "seller.productRemoved": "Igicuruzwa cyavanyweho.",
    "seller.deleteFailed": "Gusiba byanze",
    "seller.unknownError": "Ikosa ritazwi",
    "seller.delete": "Siba",
    "seller.ordersLoadFailed": "Kuzana orders byanze",
    "seller.ordersTitle": "Orders z'umucuruzi",
    "seller.ordersSubtitle": "Cunga gutegura no kuvugurura status.",
    "seller.loading": "Birimo gufungura...",
    "seller.fetchingOrders": "Birimo kuzana orders.",
    "seller.noOrdersYet": "Nta order uraboneka",
    "seller.noOrdersDesc": "Orders zirimo ibicuruzwa byawe zizagaragara hano.",
    "seller.order": "Order",
    "seller.buyer": "Umuguzi",
    "seller.total": "Igiteranyo",
    "seller.yourItems": "Ibyawe",
    "seller.orderStatus": "Status ya order",
    "seller.items": "Ibintu",
    "seller.qty": "Ingano",
    "seller.updateFailed": "Kuvugurura byanze",
    "seller.payoutsTitle": "Kwishyura & Wallet",
    "seller.payoutsSubtitle": "Cunga amafaranga winjiza n'uburyo bwo kuyakuramo.",
    "seller.backToDashboard": "Subira kuri Dashboard",
    "seller.availableBalance": "Amafaranga ahari",
    "seller.withdrawFunds": "Kuramo amafaranga",
    "seller.payoutSettings": "Igenamiterere rya payout",
    "seller.nextScheduledPayout": "Payout ikurikira",
    "seller.nextMonday": "Kuwa mbere utaha",
    "seller.automaticTransfer": "Koherezwa byikora",
    "seller.processingPeriod": "Igihe cyo gutunganya",
    "seller.transactionHistory": "Amateka y'ibikorwa",
    "seller.date": "Itariki",
    "seller.type": "Ubwoko",
    "seller.description": "Ibisobanuro",
    "seller.reference": "Reference",
    "seller.amount": "Amafaranga",
    "seller.status": "Status",
    "seller.payout": "Payout",
    "seller.sale": "Igurishwa",
    "seller.weeklySettlement": "Kwishyura kwa buri cyumweru",
    "seller.completed": "Byarangiye",
    "seller.storeSettingsPageDesc": "Cunga umwirondoro n'igenamiterere ry'iduka.",
    "seller.storeInformation": "Amakuru y'iduka",
    "seller.storeName": "Izina ry'iduka",
    "seller.supportEmail": "Email y'ubufasha",
    "seller.storeDescription": "Ibisobanuro by'iduka",
    "seller.describeStore": "Sobanura iduka ryawe...",
    "seller.branding": "Branding",
    "seller.uploadLogo": "Ohereza logo",
    "seller.uploadBanner": "Ohereza banner",
    "seller.saveChanges": "Bika impinduka",
    "sellerNew.unsupportedFile": "Dosiye itemewe",
    "sellerNew.fileTooLarge": "Dosiye nini cyane",
    "sellerNew.exceedsUploadLimit": "irenze urugero rwo kohereza",
    "sellerNew.createProduct": "Kora igicuruzwa",
    "sellerNew.fastSetup": "Gushyiraho vuba hamwe n'ibigaragara bya media na variants zoroshye.",
    "sellerNew.back": "Subira inyuma",
    "sellerNew.basics": "Ibanze",
    "sellerNew.noApprovedStore": "Nta duka ryemejwe riraboneka",
    "sellerNew.submitVendorApplication": "Banze wohereze application ya vendor ku rupapuro rwa onboarding.",
    "sellerNew.goToOnboarding": "Jya kuri onboarding",
    "sellerNew.vendor": "Vendor",
    "sellerNew.chooseVendor": "Hitamo vendor",
    "sellerNew.noStoreYet": "Nta duka uragira. Kora rimwe hepfo.",
    "sellerNew.orCreateVendor": "Cyangwa kora vendor",
    "sellerNew.vendorName": "Izina rya vendor",
    "sellerNew.vendorRequiresApproval": "Vendors bakeneye approval ya admin. Koresha onboarding.",
    "sellerNew.title": "Umutwe",
    "sellerNew.titlePlaceholder": "urugero: T-shirt ya cotton",
    "sellerNew.description": "Ibisobanuro",
    "sellerNew.descriptionPlaceholder": "Ibisobanuro bigufi kandi bisobanutse.",
    "sellerNew.category": "Category",
    "sellerNew.noCategories": "Nta categories ziboneka.",
    "sellerNew.selectCategory": "Hitamo category",
    "sellerNew.priceRwf": "Igiciro (RWF)",
    "sellerNew.stock": "Ububiko",
    "sellerNew.discountPercent": "Discount (%)",
    "sellerNew.media": "Media",
    "sellerNew.imagesVideos": "Amafoto na videwo",
    "sellerNew.dragDrop": "Kurura ushyiremo cyangwa hitamo dosiye. Kugera kuri",
    "sellerNew.imagesMax": "Amafoto ≤",
    "sellerNew.videosMax": "videwo ≤",
    "sellerNew.addMedia": "Ongeraho media",
    "sellerNew.setAsPrimary": "Gira primary",
    "sellerNew.primary": "Primary",
    "sellerNew.removeMedia": "Kuraho media",
    "sellerNew.noMediaYet": "Nta media yatoranyijwe.",
    "sellerNew.variants": "Variants",
    "sellerNew.disable": "Hagarika",
    "sellerNew.enable": "Fungura",
    "sellerNew.variantsHelp": "Ongeraho amahitamo nk'amabara na sizes kugira ngo abaguzi bahitemo vuba.",
    "sellerNew.colors": "Amabara",
    "sellerNew.addColorPlaceholder": "Ongeraho ibara (urugero Blue cyangwa #3b82f6)",
    "sellerNew.sizes": "Sizes",
    "sellerNew.addSizePlaceholder": "Ongeraho size (urugero XXL)",
    "sellerNew.variantsDisabled": "Variants zahagaritswe. Igicuruzwa kizashyirwaho nta mahitamo.",
    "sellerNew.readyToPublish": "Witeguye gutangaza",
    "sellerNew.looksGood": "Bimeze neza",
    "sellerNew.publishChecklist": "Ongeraho umutwe, igiciro, category na vendor kugira ngo utangaze.",
    "sellerNew.colorsLower": "amabara",
    "sellerNew.sizesLower": "sizes",
    "sellerNew.off": "Byazimye",
    "sellerNew.selectCategoryError": "Hitamo category",
    "sellerNew.vendorCreationRequiresApproval": "Gukora vendor bisaba approval. Koresha onboarding (/sell).",
    "sellerNew.missingVendor": "Vendor yabuze",
    "sellerNew.missingSession": "Session yabuze",
    "sellerNew.productUploaded": "Igicuruzwa cyoherejwe",
    "sellerNew.productLive": "Igicuruzwa cyawe kiri live.",
    "sellerNew.uploadFailed": "Kohereza byanze",
    "sellerNew.uploading": "Birimo koherezwa...",
    "sellerNew.publishProduct": "Tangaza igicuruzwa",
    "sellerNew.uploadingMedia": "Birimo kohereza media...",
    "sellerNew.complete": "byarangiye",

    // Admin dashboard/pages
    "admin.signInRequired": "Kwinjira birakenewe",
    "admin.authRequired": "Kwemeza admin birakenewe",
    "admin.accessDenied": "Nta burenganzira",
    "admin.privilegesRequired": "Uburenganzira bwa admin burakenewe",
    "admin.home": "Ahabanza",
    "admin.account": "Konti",
    "admin.supabaseMissing": "Supabase ntirashyirwaho",
    "admin.missingData": "Amakuru arabuze",
    "admin.notSignedIn": "Ntabwo winjiye",
    "admin.missingVendor": "Vendor yabuze",
    "admin.missingProduct": "Igicuruzwa cyabuze",
    "admin.reasonMin": "Andika impamvu ngufi nibura inyuguti 5",
    "admin.panel": "Admin Panel",
    "admin.storefront": "Urubuga rw'iduka",
    "admin.dashboardOverview": "Incamake ya dashboard",
    "admin.vendors": "Vendors",
    "admin.products": "Ibicuruzwa",
    "admin.discounts": "Discounts",
    "admin.applications": "Applications",
    "admin.approved": "Byemejwe",
    "admin.pending": "Bitegereje",
    "admin.rejected": "Byanzwe",
    "admin.revoked": "Byahagaritswe",
    "admin.category": "Category",
    "admin.stock": "Ububiko",
    "admin.allCategories": "Categories zose",
    "admin.allStock": "Stock yose",
    "admin.inStock": "Birahari",
    "admin.outOfStock": "Byarangiye",
    "admin.totalProducts": "ibicuruzwa byose",
    "admin.totalVendors": "vendors bose",
    "admin.totalValue": "Agaciro kose",
    "admin.totalSales": "Ibyagurishijwe byose",
    "admin.totalSold": "Byagurishijwe byose",
    "admin.unitsSold": "Units zagurishijwe",
    "admin.sold": "byagurishijwe",
    "admin.search": "Shakisha...",
    "admin.searchVendors": "Shakisha vendors...",
    "admin.searchCodes": "Shakisha codes...",
    "admin.noProductsFound": "Nta bicuruzwa byabonetse",
    "admin.noVendorsFound": "Nta vendor wabonetse",
    "admin.noApplicationsFound": "Nta applications yabonetse",
    "admin.vendorApplications": "Applications za vendor",
    "admin.totalApplications": "applications zose",
    "admin.loadingApplications": "Birimo kuzana applications...",
    "admin.noLocation": "Nta hantu",
    "admin.noLocationSpecified": "Nta hantu handitswe",
    "admin.applied": "Byoherejwe",
    "admin.user": "Umukoresha",
    "admin.canNowSell": "ashobora kugurisha",
    "admin.isNowApproved": "yamaze kwemezwa",
    "admin.approve": "Emeza",
    "admin.reject": "Anga",
    "admin.restore": "Subizaho",
    "admin.revoke": "Hagarika",
    "admin.vendorCanSellAgain": "Vendor ashobora kongera kugurisha",
    "admin.vendorCannotSell": "Vendor ntashobora kugurisha",
    "admin.removeVendor": "Kuraho vendor",
    "admin.sales": "Ibyagurishijwe",
    "admin.revenue": "Amafaranga yinjiye",
    "admin.discountCode": "Discount code",
    "admin.discountCodes": "Discount codes",
    "admin.createDiscountCode": "Kora discount code",
    "admin.created": "Byakozwe",
    "admin.createdLower": "byakozwe",
    "admin.code": "Code",
    "admin.codeMin": "Code igomba kuba nibura inyuguti 3",
    "admin.description": "Ibisobanuro",
    "admin.type": "Ubwoko",
    "admin.percentage": "Ijanisha",
    "admin.fixedAmountRwf": "Amafaranga ahamye (RWF)",
    "admin.value": "Agaciro",
    "admin.minSubtotal": "Subtotal nto",
    "admin.minSubtotalRwf": "Subtotal nto (RWF)",
    "admin.maxRedemptionsOptional": "Max redemptions (si ngombwa)",
    "admin.redeemed": "Byakoreshejwe",
    "admin.actions": "Ibikorwa",
    "admin.create": "Kora",
    "admin.deleteCodeConfirm": "Siba code",
    "admin.updated": "Byavuguruwe",
    "admin.deleted": "Byasibwe",
    "admin.failed": "Byanze",
    "admin.unknownError": "Ikosa ritazwi",
    "admin.deleteProduct": "Siba igicuruzwa",
    "admin.deleteProductDesc": "Ibi bizakuraho igicuruzwa kandi bimenyeshe vendor.",
    "admin.productRemoved": "Igicuruzwa cyavanyweho",
    "admin.deleteVendor": "Siba vendor",
    "admin.deleteVendorDesc": "Ibi bizakuraho vendor n'ibicuruzwa bye. Orders zisanzwe zizagumaho.",
    "admin.vendorRemoved": "Vendor yavanyweho",
    "admin.reasonForRemoval": "Impamvu yo gukuraho",
    "admin.explainPolicy": "Sobanura kutubahiriza policy...",
    "admin.cancel": "Hagarika",
    "admin.all": "Byose",
    "admin.missingCategory": "Category irabuze",
    "auth.login": "Injira",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("iwanyu_language");
    return (saved as Language) || "rw"; // Default to Kinyarwanda
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("iwanyu_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language === "rw" ? "rw" : "en";
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
